/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PatchedPriceUpdatePricePer
import org.openapitools.client.models.BlankEnum
import org.openapitools.client.models.PricePerEnum

class PatchedPriceUpdatePricePerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PatchedPriceUpdatePricePer
        //val modelInstance = PatchedPriceUpdatePricePer()

    }
}
