/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PriceUpdate
import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.PatchedPriceUpdatePricePer

class PriceUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PriceUpdate
        //val modelInstance = PriceUpdate()

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `priceIsDiscounted`
        should("test priceIsDiscounted") {
            // uncomment below to test the property
            //modelInstance.priceIsDiscounted shouldBe ("TODO")
        }

        // to test the property `priceWithoutDiscount`
        should("test priceWithoutDiscount") {
            // uncomment below to test the property
            //modelInstance.priceWithoutDiscount shouldBe ("TODO")
        }

        // to test the property `pricePer`
        should("test pricePer") {
            // uncomment below to test the property
            //modelInstance.pricePer shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

    }
}
