/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PriceStats

class PriceStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PriceStats
        //val modelInstance = PriceStats()

        // to test the property `priceCount`
        should("test priceCount") {
            // uncomment below to test the property
            //modelInstance.priceCount shouldBe ("TODO")
        }

        // to test the property `priceMin`
        should("test priceMin") {
            // uncomment below to test the property
            //modelInstance.priceMin shouldBe ("TODO")
        }

        // to test the property `priceMax`
        should("test priceMax") {
            // uncomment below to test the property
            //modelInstance.priceMax shouldBe ("TODO")
        }

        // to test the property `priceAvg`
        should("test priceAvg") {
            // uncomment below to test the property
            //modelInstance.priceAvg shouldBe ("TODO")
        }

    }
}
