/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PriceCreate
import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.PatchedPriceUpdatePricePer
import org.openapitools.client.models.PriceCreateLocationOsmType

class PriceCreateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PriceCreate
        //val modelInstance = PriceCreate()

        // to test the property `proofId`
        should("test proofId") {
            // uncomment below to test the property
            //modelInstance.proofId shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `priceIsDiscounted`
        should("test priceIsDiscounted") {
            // uncomment below to test the property
            //modelInstance.priceIsDiscounted shouldBe ("TODO")
        }

        // to test the property `priceWithoutDiscount`
        should("test priceWithoutDiscount") {
            // uncomment below to test the property
            //modelInstance.priceWithoutDiscount shouldBe ("TODO")
        }

        // to test the property `pricePer`
        should("test pricePer") {
            // uncomment below to test the property
            //modelInstance.pricePer shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `productCode`
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `categoryTag`
        should("test categoryTag") {
            // uncomment below to test the property
            //modelInstance.categoryTag shouldBe ("TODO")
        }

        // to test the property `labelsTags`
        should("test labelsTags") {
            // uncomment below to test the property
            //modelInstance.labelsTags shouldBe ("TODO")
        }

        // to test the property `originsTags`
        should("test originsTags") {
            // uncomment below to test the property
            //modelInstance.originsTags shouldBe ("TODO")
        }

        // to test the property `locationOsmId`
        should("test locationOsmId") {
            // uncomment below to test the property
            //modelInstance.locationOsmId shouldBe ("TODO")
        }

        // to test the property `locationOsmType`
        should("test locationOsmType") {
            // uncomment below to test the property
            //modelInstance.locationOsmType shouldBe ("TODO")
        }

    }
}
