/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductFullSource
import org.openapitools.client.models.BlankEnum
import org.openapitools.client.models.SourceEnum

class ProductFullSourceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductFullSource
        //val modelInstance = ProductFullSource()

    }
}
