/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProofFull
import org.openapitools.client.models.Location
import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.PriceCreateLocationOsmType
import org.openapitools.client.models.TypeEnum

class ProofFullTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProofFull
        //val modelInstance = ProofFull()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `locationId`
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `updated`
        should("test updated") {
            // uncomment below to test the property
            //modelInstance.updated shouldBe ("TODO")
        }

        // to test the property `filePath`
        should("test filePath") {
            // uncomment below to test the property
            //modelInstance.filePath shouldBe ("TODO")
        }

        // to test the property `mimetype`
        should("test mimetype") {
            // uncomment below to test the property
            //modelInstance.mimetype shouldBe ("TODO")
        }

        // to test the property `imageThumbPath`
        should("test imageThumbPath") {
            // uncomment below to test the property
            //modelInstance.imageThumbPath shouldBe ("TODO")
        }

        // to test the property `locationOsmId`
        should("test locationOsmId") {
            // uncomment below to test the property
            //modelInstance.locationOsmId shouldBe ("TODO")
        }

        // to test the property `locationOsmType`
        should("test locationOsmType") {
            // uncomment below to test the property
            //modelInstance.locationOsmType shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `priceCount`
        should("test priceCount") {
            // uncomment below to test the property
            //modelInstance.priceCount shouldBe ("TODO")
        }

        // to test the property `owner`
        should("test owner") {
            // uncomment below to test the property
            //modelInstance.owner shouldBe ("TODO")
        }

        // to test the property `created`
        should("test created") {
            // uncomment below to test the property
            //modelInstance.created shouldBe ("TODO")
        }

    }
}
