/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SessionFull

class SessionFullTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionFull
        //val modelInstance = SessionFull()

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `token`
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `created`
        should("test created") {
            // uncomment below to test the property
            //modelInstance.created shouldBe ("TODO")
        }

        // to test the property `lastUsed`
        should("test lastUsed") {
            // uncomment below to test the property
            //modelInstance.lastUsed shouldBe ("TODO")
        }

    }
}
