/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TotalStats

class TotalStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TotalStats
        //val modelInstance = TotalStats()

        // to test the property `updated`
        should("test updated") {
            // uncomment below to test the property
            //modelInstance.updated shouldBe ("TODO")
        }

        // to test the property `priceCount`
        should("test priceCount") {
            // uncomment below to test the property
            //modelInstance.priceCount shouldBe ("TODO")
        }

        // to test the property `priceBarcodeCount`
        should("test priceBarcodeCount") {
            // uncomment below to test the property
            //modelInstance.priceBarcodeCount shouldBe ("TODO")
        }

        // to test the property `priceCategoryCount`
        should("test priceCategoryCount") {
            // uncomment below to test the property
            //modelInstance.priceCategoryCount shouldBe ("TODO")
        }

        // to test the property `productCount`
        should("test productCount") {
            // uncomment below to test the property
            //modelInstance.productCount shouldBe ("TODO")
        }

        // to test the property `productWithPriceCount`
        should("test productWithPriceCount") {
            // uncomment below to test the property
            //modelInstance.productWithPriceCount shouldBe ("TODO")
        }

        // to test the property `locationCount`
        should("test locationCount") {
            // uncomment below to test the property
            //modelInstance.locationCount shouldBe ("TODO")
        }

        // to test the property `locationWithPriceCount`
        should("test locationWithPriceCount") {
            // uncomment below to test the property
            //modelInstance.locationWithPriceCount shouldBe ("TODO")
        }

        // to test the property `proofCount`
        should("test proofCount") {
            // uncomment below to test the property
            //modelInstance.proofCount shouldBe ("TODO")
        }

        // to test the property `proofWithPriceCount`
        should("test proofWithPriceCount") {
            // uncomment below to test the property
            //modelInstance.proofWithPriceCount shouldBe ("TODO")
        }

        // to test the property `userCount`
        should("test userCount") {
            // uncomment below to test the property
            //modelInstance.userCount shouldBe ("TODO")
        }

        // to test the property `userWithPriceCount`
        should("test userWithPriceCount") {
            // uncomment below to test the property
            //modelInstance.userWithPriceCount shouldBe ("TODO")
        }

    }
}
