/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.User

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `priceCount`
        should("test priceCount") {
            // uncomment below to test the property
            //modelInstance.priceCount shouldBe ("TODO")
        }

        // to test the property `locationCount`
        should("test locationCount") {
            // uncomment below to test the property
            //modelInstance.locationCount shouldBe ("TODO")
        }

        // to test the property `productCount`
        should("test productCount") {
            // uncomment below to test the property
            //modelInstance.productCount shouldBe ("TODO")
        }

        // to test the property `proofCount`
        should("test proofCount") {
            // uncomment below to test the property
            //modelInstance.proofCount shouldBe ("TODO")
        }

    }
}
