/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AuthApi
import org.openapitools.client.models.Login
import org.openapitools.client.models.SessionFull
import org.openapitools.client.models.SessionResponse

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test authCreate
        should("test authCreate") {
            // uncomment below to test authCreate
            //val login : Login =  // Login | 
            //val result : SessionResponse = apiInstance.authCreate(login)
            //result shouldBe ("TODO")
        }

        // to test sessionDestroy
        should("test sessionDestroy") {
            // uncomment below to test sessionDestroy
            //apiInstance.sessionDestroy()
        }

        // to test sessionRetrieve
        should("test sessionRetrieve") {
            // uncomment below to test sessionRetrieve
            //val result : SessionFull = apiInstance.sessionRetrieve()
            //result shouldBe ("TODO")
        }

    }
}
