/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.LocationsApi
import org.openapitools.client.models.Location
import org.openapitools.client.models.LocationCreate
import org.openapitools.client.models.PaginatedLocationList

class LocationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LocationsApi
        //val apiInstance = LocationsApi()

        // to test locationsCreate
        should("test locationsCreate") {
            // uncomment below to test locationsCreate
            //val locationCreate : LocationCreate =  // LocationCreate | 
            //val result : LocationCreate = apiInstance.locationsCreate(locationCreate)
            //result shouldBe ("TODO")
        }

        // to test locationsList
        should("test locationsList") {
            // uncomment below to test locationsList
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | Which field to use when ordering the results.
            //val osmAddressCityLike : kotlin.String = osmAddressCityLike_example // kotlin.String | 
            //val osmAddressCountryLike : kotlin.String = osmAddressCountryLike_example // kotlin.String | 
            //val osmNameLike : kotlin.String = osmNameLike_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | A page number within the paginated result set.
            //val priceCount : kotlin.Int = 56 // kotlin.Int | 
            //val priceCountGte : kotlin.Int = 56 // kotlin.Int | 
            //val priceCountLte : kotlin.Int = 56 // kotlin.Int | 
            //val size : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val result : PaginatedLocationList = apiInstance.locationsList(orderBy, osmAddressCityLike, osmAddressCountryLike, osmNameLike, page, priceCount, priceCountGte, priceCountLte, size)
            //result shouldBe ("TODO")
        }

        // to test locationsOsmRetrieve
        should("test locationsOsmRetrieve") {
            // uncomment below to test locationsOsmRetrieve
            //val osmId : kotlin.String = osmId_example // kotlin.String | 
            //val osmType : kotlin.String = osmType_example // kotlin.String | 
            //val result : Location = apiInstance.locationsOsmRetrieve(osmId, osmType)
            //result shouldBe ("TODO")
        }

        // to test locationsRetrieve
        should("test locationsRetrieve") {
            // uncomment below to test locationsRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this Location.
            //val result : Location = apiInstance.locationsRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
