/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ProductsApi
import org.openapitools.client.models.PaginatedProductFullList
import org.openapitools.client.models.ProductFull

class ProductsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductsApi
        //val apiInstance = ProductsApi()

        // to test productsCodeRetrieve
        should("test productsCodeRetrieve") {
            // uncomment below to test productsCodeRetrieve
            //val code : kotlin.String = code_example // kotlin.String | 
            //val result : ProductFull = apiInstance.productsCodeRetrieve(code)
            //result shouldBe ("TODO")
        }

        // to test productsList
        should("test productsList") {
            // uncomment below to test productsList
            //val brandsLike : kotlin.String = brandsLike_example // kotlin.String | 
            //val brandsTagsContains : kotlin.String = brandsTagsContains_example // kotlin.String | 
            //val categoriesTagsContains : kotlin.String = categoriesTagsContains_example // kotlin.String | 
            //val code : kotlin.String = code_example // kotlin.String | 
            //val ecoscoreGrade : kotlin.String = ecoscoreGrade_example // kotlin.String | 
            //val labelsTagsContains : kotlin.String = labelsTagsContains_example // kotlin.String | 
            //val novaGroup : kotlin.Int = 56 // kotlin.Int | 
            //val nutriscoreGrade : kotlin.String = nutriscoreGrade_example // kotlin.String | 
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | Which field to use when ordering the results.
            //val page : kotlin.Int = 56 // kotlin.Int | A page number within the paginated result set.
            //val priceCount : kotlin.Int = 56 // kotlin.Int | 
            //val priceCountGte : kotlin.Int = 56 // kotlin.Int | 
            //val priceCountLte : kotlin.Int = 56 // kotlin.Int | 
            //val productNameLike : kotlin.String = productNameLike_example // kotlin.String | 
            //val size : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val source : kotlin.String = source_example // kotlin.String | * `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro
            //val uniqueScansNGte : kotlin.Int = 56 // kotlin.Int | 
            //val result : PaginatedProductFullList = apiInstance.productsList(brandsLike, brandsTagsContains, categoriesTagsContains, code, ecoscoreGrade, labelsTagsContains, novaGroup, nutriscoreGrade, orderBy, page, priceCount, priceCountGte, priceCountLte, productNameLike, size, source, uniqueScansNGte)
            //result shouldBe ("TODO")
        }

        // to test productsRetrieve
        should("test productsRetrieve") {
            // uncomment below to test productsRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this Product.
            //val result : ProductFull = apiInstance.productsRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
