/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StatusApi
import org.openapitools.client.models.Status

class StatusApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatusApi
        //val apiInstance = StatusApi()

        // to test statusRetrieve
        should("test statusRetrieve") {
            // uncomment below to test statusRetrieve
            //val result : Status = apiInstance.statusRetrieve()
            //result shouldBe ("TODO")
        }

    }
}
