/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StatsApi
import org.openapitools.client.models.TotalStats

class StatsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatsApi
        //val apiInstance = StatsApi()

        // to test statsRetrieve
        should("test statsRetrieve") {
            // uncomment below to test statsRetrieve
            //val result : TotalStats = apiInstance.statsRetrieve()
            //result shouldBe ("TODO")
        }

    }
}
