/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UsersApi
import org.openapitools.client.models.PaginatedUserList

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test usersList
        should("test usersList") {
            // uncomment below to test usersList
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | Which field to use when ordering the results.
            //val page : kotlin.Int = 56 // kotlin.Int | A page number within the paginated result set.
            //val priceCount : kotlin.Int = 56 // kotlin.Int | 
            //val priceCountGte : kotlin.Int = 56 // kotlin.Int | 
            //val priceCountLte : kotlin.Int = 56 // kotlin.Int | 
            //val size : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val result : PaginatedUserList = apiInstance.usersList(orderBy, page, priceCount, priceCountGte, priceCountLte, size)
            //result shouldBe ("TODO")
        }

    }
}
