/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LocationOsmTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param osmId 
 * @param osmType 
 */


data class LocationCreate (

    @Json(name = "osm_id")
    val osmId: kotlin.Long,

    @Json(name = "osm_type")
    val osmType: LocationOsmTypeEnum

) {


}

