/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `NODE` - NODE * `WAY` - WAY * `RELATION` - RELATION
 *
 * Values: NODE,WAY,RELATION
 */

@JsonClass(generateAdapter = false)
enum class LocationOsmTypeEnum(val value: kotlin.String) {

    @Json(name = "NODE")
    NODE("NODE"),

    @Json(name = "WAY")
    WAY("WAY"),

    @Json(name = "RELATION")
    RELATION("RELATION");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LocationOsmTypeEnum) "$data" else null

        /**
         * Returns a valid [LocationOsmTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LocationOsmTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

