/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Location
import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.PatchedPriceUpdatePricePer
import org.openapitools.client.models.PriceCreateLocationOsmType
import org.openapitools.client.models.ProductFull
import org.openapitools.client.models.Proof

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param productId 
 * @param locationId 
 * @param proofId 
 * @param product 
 * @param location 
 * @param proof 
 * @param updated 
 * @param productCode 
 * @param productName 
 * @param categoryTag 
 * @param labelsTags 
 * @param originsTags 
 * @param price 
 * @param priceIsDiscounted 
 * @param priceWithoutDiscount 
 * @param pricePer 
 * @param currency 
 * @param locationOsmId 
 * @param locationOsmType 
 * @param date 
 * @param owner 
 * @param created 
 */


data class PriceFull (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "product_id")
    val productId: kotlin.Int,

    @Json(name = "location_id")
    val locationId: kotlin.Int,

    @Json(name = "proof_id")
    val proofId: kotlin.Int,

    @Json(name = "product")
    val product: ProductFull,

    @Json(name = "location")
    val location: Location,

    @Json(name = "proof")
    val proof: Proof,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime,

    @Json(name = "product_code")
    val productCode: kotlin.String? = null,

    @Json(name = "product_name")
    val productName: kotlin.String? = null,

    @Json(name = "category_tag")
    val categoryTag: kotlin.String? = null,

    @Json(name = "labels_tags")
    val labelsTags: kotlin.Any? = null,

    @Json(name = "origins_tags")
    val originsTags: kotlin.Any? = null,

    @Json(name = "price")
    val price: kotlin.Double? = null,

    @Json(name = "price_is_discounted")
    val priceIsDiscounted: kotlin.Boolean? = null,

    @Json(name = "price_without_discount")
    val priceWithoutDiscount: kotlin.Double? = null,

    @Json(name = "price_per")
    val pricePer: PatchedPriceUpdatePricePer? = null,

    @Json(name = "currency")
    val currency: PatchedPriceUpdateCurrency? = null,

    @Json(name = "location_osm_id")
    val locationOsmId: kotlin.Long? = null,

    @Json(name = "location_osm_type")
    val locationOsmType: PriceCreateLocationOsmType? = null,

    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null

) {


}

