/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.PatchedPriceUpdatePricePer
import org.openapitools.client.models.PriceCreateLocationOsmType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param proofId 
 * @param price 
 * @param priceIsDiscounted 
 * @param priceWithoutDiscount 
 * @param pricePer 
 * @param currency 
 * @param date 
 * @param productCode 
 * @param productName 
 * @param categoryTag 
 * @param labelsTags 
 * @param originsTags 
 * @param locationOsmId 
 * @param locationOsmType 
 */


data class PriceCreate (

    @Json(name = "proof_id")
    val proofId: kotlin.Int,

    @Json(name = "price")
    val price: kotlin.Double? = null,

    @Json(name = "price_is_discounted")
    val priceIsDiscounted: kotlin.Boolean? = null,

    @Json(name = "price_without_discount")
    val priceWithoutDiscount: kotlin.Double? = null,

    @Json(name = "price_per")
    val pricePer: PatchedPriceUpdatePricePer? = null,

    @Json(name = "currency")
    val currency: PatchedPriceUpdateCurrency? = null,

    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "product_code")
    val productCode: kotlin.String? = null,

    @Json(name = "product_name")
    val productName: kotlin.String? = null,

    @Json(name = "category_tag")
    val categoryTag: kotlin.String? = null,

    @Json(name = "labels_tags")
    val labelsTags: kotlin.Any? = null,

    @Json(name = "origins_tags")
    val originsTags: kotlin.Any? = null,

    @Json(name = "location_osm_id")
    val locationOsmId: kotlin.Long? = null,

    @Json(name = "location_osm_type")
    val locationOsmType: PriceCreateLocationOsmType? = null

) {


}

