/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProductFullSource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param code 
 * @param updated 
 * @param source 
 * @param productName 
 * @param imageUrl 
 * @param productQuantity 
 * @param productQuantityUnit 
 * @param categoriesTags 
 * @param brands 
 * @param brandsTags 
 * @param labelsTags 
 * @param nutriscoreGrade 
 * @param ecoscoreGrade 
 * @param novaGroup 
 * @param uniqueScansN 
 * @param priceCount 
 * @param locationCount 
 * @param userCount 
 * @param proofCount 
 * @param created 
 */


data class ProductFull (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime,

    @Json(name = "source")
    val source: ProductFullSource? = null,

    @Json(name = "product_name")
    val productName: kotlin.String? = null,

    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "product_quantity")
    val productQuantity: kotlin.Int? = null,

    @Json(name = "product_quantity_unit")
    val productQuantityUnit: kotlin.String? = null,

    @Json(name = "categories_tags")
    val categoriesTags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "brands")
    val brands: kotlin.String? = null,

    @Json(name = "brands_tags")
    val brandsTags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "labels_tags")
    val labelsTags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "nutriscore_grade")
    val nutriscoreGrade: kotlin.String? = null,

    @Json(name = "ecoscore_grade")
    val ecoscoreGrade: kotlin.String? = null,

    @Json(name = "nova_group")
    val novaGroup: kotlin.Int? = null,

    @Json(name = "unique_scans_n")
    val uniqueScansN: kotlin.Int? = null,

    @Json(name = "price_count")
    val priceCount: kotlin.Int? = null,

    @Json(name = "location_count")
    val locationCount: kotlin.Int? = null,

    @Json(name = "user_count")
    val userCount: kotlin.Int? = null,

    @Json(name = "proof_count")
    val proofCount: kotlin.Int? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null

) {


}

