/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.TypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param currency 
 * @param date 
 */


data class ProofUpdate (

    @Json(name = "type")
    val type: TypeEnum,

    @Json(name = "currency")
    val currency: PatchedPriceUpdateCurrency? = null,

    @Json(name = "date")
    val date: java.time.LocalDate? = null

) {


}

