/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Location
import org.openapitools.client.models.PatchedPriceUpdateCurrency
import org.openapitools.client.models.PriceCreateLocationOsmType
import org.openapitools.client.models.TypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param locationId 
 * @param location 
 * @param type 
 * @param updated 
 * @param filePath 
 * @param mimetype 
 * @param imageThumbPath 
 * @param locationOsmId 
 * @param locationOsmType 
 * @param date 
 * @param currency 
 * @param priceCount 
 * @param owner 
 * @param created 
 */


data class ProofFull (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "location_id")
    val locationId: kotlin.Int,

    @Json(name = "location")
    val location: Location,

    @Json(name = "type")
    val type: TypeEnum,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime,

    @Json(name = "file_path")
    val filePath: kotlin.String? = null,

    @Json(name = "mimetype")
    val mimetype: kotlin.String? = null,

    @Json(name = "image_thumb_path")
    val imageThumbPath: kotlin.String? = null,

    @Json(name = "location_osm_id")
    val locationOsmId: kotlin.Long? = null,

    @Json(name = "location_osm_type")
    val locationOsmType: PriceCreateLocationOsmType? = null,

    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    @Json(name = "currency")
    val currency: PatchedPriceUpdateCurrency? = null,

    @Json(name = "price_count")
    val priceCount: kotlin.Int? = null,

    @Json(name = "owner")
    val owner: kotlin.String? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null

) {


}

