/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param token 
 * @param created 
 * @param lastUsed 
 */


data class SessionFull (

    @Json(name = "user_id")
    val userId: kotlin.String,

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "created")
    val created: kotlin.String,

    @Json(name = "last_used")
    val lastUsed: kotlin.String

) {


}

