/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `off` - off * `obf` - obf * `opff` - opff * `opf` - opf * `off_pro` - off_pro
 *
 * Values: off,obf,opff,opf,off_pro
 */

@JsonClass(generateAdapter = false)
enum class SourceEnum(val value: kotlin.String) {

    @Json(name = "off")
    off("off"),

    @Json(name = "obf")
    obf("obf"),

    @Json(name = "opff")
    opff("opff"),

    @Json(name = "opf")
    opf("opf"),

    @Json(name = "off_pro")
    off_pro("off_pro");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SourceEnum) "$data" else null

        /**
         * Returns a valid [SourceEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SourceEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

