/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param updated 
 * @param priceCount 
 * @param priceBarcodeCount 
 * @param priceCategoryCount 
 * @param productCount 
 * @param productWithPriceCount 
 * @param locationCount 
 * @param locationWithPriceCount 
 * @param proofCount 
 * @param proofWithPriceCount 
 * @param userCount 
 * @param userWithPriceCount 
 */


data class TotalStats (

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime,

    @Json(name = "price_count")
    val priceCount: kotlin.Int? = null,

    @Json(name = "price_barcode_count")
    val priceBarcodeCount: kotlin.Int? = null,

    @Json(name = "price_category_count")
    val priceCategoryCount: kotlin.Int? = null,

    @Json(name = "product_count")
    val productCount: kotlin.Int? = null,

    @Json(name = "product_with_price_count")
    val productWithPriceCount: kotlin.Int? = null,

    @Json(name = "location_count")
    val locationCount: kotlin.Int? = null,

    @Json(name = "location_with_price_count")
    val locationWithPriceCount: kotlin.Int? = null,

    @Json(name = "proof_count")
    val proofCount: kotlin.Int? = null,

    @Json(name = "proof_with_price_count")
    val proofWithPriceCount: kotlin.Int? = null,

    @Json(name = "user_count")
    val userCount: kotlin.Int? = null,

    @Json(name = "user_with_price_count")
    val userWithPriceCount: kotlin.Int? = null

) {


}

