/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `PRICE_TAG` - PRICE_TAG * `RECEIPT` - RECEIPT * `GDPR_REQUEST` - GDPR_REQUEST * `SHOP_IMPORT` - SHOP_IMPORT
 *
 * Values: PRICE_TAG,RECEIPT,GDPR_REQUEST,SHOP_IMPORT
 */

@JsonClass(generateAdapter = false)
enum class TypeEnum(val value: kotlin.String) {

    @Json(name = "PRICE_TAG")
    PRICE_TAG("PRICE_TAG"),

    @Json(name = "RECEIPT")
    RECEIPT("RECEIPT"),

    @Json(name = "GDPR_REQUEST")
    GDPR_REQUEST("GDPR_REQUEST"),

    @Json(name = "SHOP_IMPORT")
    SHOP_IMPORT("SHOP_IMPORT");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TypeEnum) "$data" else null

        /**
         * Returns a valid [TypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

